### ISSUE TITLE
Igdm issue

### ISSUE THREAD

**Issue by freestilo** [igdmapps/igdm-pro-release#73]
When I open the IGDM application, it loads at first but after a while everything disappears and I have a white screen in the application even with bought License key.

**Comment by ifedapoolarewaju** [comment]
Hello,Sorry to hear that you’re facing issues using IGdm Pro.Could you please share:1. What type of machine you use (windows, mac, linux)?2. A screenshot of the blank page you see3. What action triggers the blank page? A button you click? Or scrolling through chat list?4. What version of IGdm Pro you have installedOn 11 Nov 2023, at 19:02, freestilo ***@***.***> wrote:﻿
When I open the IGDM application, it loads at first but after a while everything disappears and I have a white screen in the application even with bought License key.

**Comment by freestilo** [comment]
![image](https://github.com/igdmapps/igdm-pro-release/assets/72163473/9be77c7e-4708-49dc-8485-1af0ba16160d)
![image](https://github.com/igdmapps/igdm-pro-release/assets/72163473/e5fff097-d8ad-489d-880a-057afa27a864)
First screen is when I start running application and second screen is like 5 seconds later. It triggers by it self. Im using Windows.

**Comment by freestilo** [comment]
And i just downloaded newest version of IGDM i bought it today.

**Comment by ifedapoolarewaju** [comment]
Thank you for sharing this info.It must be that there’s an issue with loading your chat list.I’ll investigate and roll out a fix in a couple of hours. Please bear with me as I do so.On 11 Nov 2023, at 19:23, freestilo ***@***.***> wrote:﻿
And i just downloaded newest version of IGDM i bought it today.

**Comment by freestilo** [comment]
Ok thanks ! let me know if you will be done !:)

**Comment by ifedapoolarewaju** [comment]
Hi @freestilo 👋🏽 

Apologies for taking a while to get back to you.

I have released a new version that will no longer display a blank screen.
Instead, when an error occurs, it will display the error message in a pop-up, then you can take a screenshot of that error and post it here so I can easily know what area needs to be fixed.

You can download the [new version here](https://github.com/igdmapps/igdm-pro-release/releases/download/v3.0.9/IGdm-Pro-Setup-3.0.9.exe).

Please install and let me know how it goes.
I look forward to your feedback so I can get this issue out of the way ASAP.

Thank you very much for your patience.

**Comment by freestilo** [comment]
Its okay, take your time. 
![image](https://github.com/igdmapps/igdm-pro-release/assets/72163473/48563978-cd99-41c7-94e4-b2f64d9421da)
There it is

**Comment by ifedapoolarewaju** [comment]
thank you for this.

Quick question, does the screen still go blank when you see this pop-up? Or are you able to do other things such as viewing "Unfollowers", etc.

My expectation is that everything else should be functional except that your chat list (on the left) is blank.

**Comment by freestilo** [comment]
![image](https://github.com/igdmapps/igdm-pro-release/assets/72163473/d25c115a-5d69-4431-99ca-2d7b794ba937)
Yep it still goes blank.

**Comment by freestilo** [comment]
![image](https://github.com/igdmapps/igdm-pro-release/assets/72163473/f8cd781b-998a-4e93-b267-8769bae1a037)
Now i cant even see thing in edit etc..

**Comment by ifedapoolarewaju** [comment]
Alright, since the entire screen is still blank, it seems I didn't properly collect the error before displaying in the pop-up.

I have just released [another version](https://github.com/igdmapps/igdm-pro-release/releases/download/v3.0.10/IGdm-Pro-Setup-3.0.10.exe) that corrects this. Could you be so kind to install this new version and share a screenshot of the pop-up. Also please let me know if the entire screen still goes blank in this case.

You can download the [new version here](https://github.com/igdmapps/igdm-pro-release/releases/download/v3.0.10/IGdm-Pro-Setup-3.0.10.exe)

**Comment by freestilo** [comment]
![image](https://github.com/igdmapps/igdm-pro-release/assets/72163473/707f5777-721c-4207-8f31-732295acb244)
Well huge error list but new its not blank anymoore but cannot see chats still

**Comment by freestilo** [comment]
Hope its gonna get fixed as soonest possible

**Comment by ifedapoolarewaju** [comment]
Oh snap, I didn't get an email notification for your last screenshot. Taking a look at it now.

And yes, this is the actual error I needed. Will roll out a fix soon

**Comment by freestilo** [comment]
Okay, let me know when !:)

**Comment by ifedapoolarewaju** [comment]
Hi @freestilo , I have now [released a fix](https://github.com/igdmapps/igdm-pro-release/releases/download/v3.0.11/IGdm-Pro-Setup-3.0.11.exe) for the error you've shared.

You can download [the fix here](https://github.com/igdmapps/igdm-pro-release/releases/download/v3.0.11/IGdm-Pro-Setup-3.0.11.exe).

While I don't expect any errors, If for any reason another error pops-up, then it means there are other issues that need to be fixed.

But please let me know if it does indeed work for you.

Thank you for your patience.

**Comment by ifedapoolarewaju** [comment]
Hi @freestilo, did you get the chance to install the fix yet?

I'm not sure if you saw my last comment, so I'm just posting this again to bring it up your radar. : )

**Comment by freestilo** [comment]
Sorry man, I live in Europe (Czech republic) and I think we got differrent time zones, i work from 4am to 3pm. Didnt had chance to try that. 

_< Image Removed >_

It works fine ! i just need to test out if i can see even Sent direct photos and videos and everything will be perfect <3. So much thank you

**Comment by freestilo** [comment]
![image](https://github.com/igdmapps/igdm-pro-release/assets/72163473/e770aaac-d77d-4b28-933b-f25484bbb0b5)
Can u somehow upgrade that i could see that photo in bigger shape and with higher quality ?

**Comment by freestilo** [comment]
![image](https://github.com/igdmapps/igdm-pro-release/assets/72163473/4d4b6ee0-94ce-461f-869e-b795e2233897)
When i download photo, it looks like this

**Comment by ifedapoolarewaju** [comment]
Hi @freestilo great to hear that it now works out fine for you 🥳 

Thank you for helping provide the info needed to resolve this 🙏🏽

**Comment by ifedapoolarewaju** [comment]
> Sorry man, I live in Europe (Czech republic) and I think we got differrent time zones, i work from 4am to 3pm. Didnt had chance to try that.
> 
> _< Image Removed >_
> 
> It works fine ! i just need to test out if i can see even Sent direct photos and videos and everything will be perfect <3. So much thank you

I have gone ahead to remove the screenshot from this post since this is a public channel and it contains chat list from your personal conversation

**Comment by ifedapoolarewaju** [comment]
> ![image](https://user-images.githubusercontent.com/72163473/282494012-e770aaac-d77d-4b28-933b-f25484bbb0b5.png) Can u somehow upgrade that i could see that photo in bigger shape and with higher quality ?

Hmm, yes this must have been an oversight. The general goal is to indeed download images in the highest quality.
What kind of message was this? Story shared? Direct image uploaded? Disappearing message?

**Comment by freestilo** [comment]
You didnt had to. Idc about personal information, there wasnt nothing to see XD but thanks i guess. Idk how to called that, direct message that u can open for unlimited time twice and it will desapear. It would be awesome, if you can upgrade that somehow ^^!  it would be cool even for bomb photos that u can open for limited time. Thanks boss

**Comment by ifedapoolarewaju** [comment]
Ah ok, that sounds like disappearing photos then. I'll look into a fix and share with you once published

**Comment by freestilo** [comment]
Thanks you ? how can i repay you for all of this ? some rewiev or something like that ?

**Comment by freestilo** [comment]
So how is it look like ? could tell me when I can expect that update ? ty

**Comment by ifedapoolarewaju** [comment]
> Thanks you ? how can i repay you for all of this ? some rewiev or something like that ?

Oh yes please! You can leave a review on [Product Hunt](https://www.producthunt.com/products/igdm/reviews).
It'll go a long way. 🙏🏽

**Comment by ifedapoolarewaju** [comment]
> So how is it look like ? could tell me when I can expect that update ? ty

I should be able to roll out a fix for this by Thursday. Does this work for you?

**Comment by freestilo** [comment]
Okay i will write review in future <3. Yeah its okay ^^ ty a lot

**Comment by ifedapoolarewaju** [comment]
Hi @freestilo the image quality issue has now been fixed in the latest release.
You can [download it here](https://github.com/igdmapps/igdm-pro-release/releases/download/v3.0.12/IGdm-Pro-Setup-3.0.12.exe).

Are you able to test it again with that image from 2 days ago?

**Comment by freestilo** [comment]
![image](https://github.com/igdmapps/igdm-pro-release/assets/72163473/5424a5eb-c35a-4099-9a0e-e4354f59a3df)
![image](https://github.com/igdmapps/igdm-pro-release/assets/72163473/b8446a39-cb65-4b7d-add2-50210329b0a4)
Still same for me

**Comment by ifedapoolarewaju** [comment]
Hmm, I’m surprised. Is the quality of the image any better on the phone app? Can you share the phone version for comparison?On 17 Nov 2023, at 20:35, freestilo ***@***.***> wrote:﻿


Still same for me

**Comment by freestilo** [comment]
I never used that on phone that app

**Comment by freestilo** [comment]
I just need that on PC, im not planning using that on phone

**Comment by ifedapoolarewaju** [comment]
Ok, I'm just trying to validate the quality of the original image sent, to avoid a wild goose chase. Because it may be that this is the quality of the image which was sent as well.

**Comment by freestilo** [comment]
Can u send me, where i can download that on my iPhone ?

**Comment by ifedapoolarewaju** [comment]
Oh I meant the Instagram mobile app

**Comment by freestilo** [comment]
1st is from IGDM pro
![image](https://github.com/igdmapps/igdm-pro-release/assets/72163473/60063e72-b474-40af-b4b6-44e39cf6c70d)
2nd is from INSTAGRAM
![image](https://github.com/igdmapps/igdm-pro-release/assets/72163473/6e53a543-d3f5-45c3-8de6-65a20b1b7747)

**Comment by ifedapoolarewaju** [comment]
Hmm I see. I’ll investigate furtherOn 17 Nov 2023, at 22:02, freestilo ***@***.***> wrote:﻿
1st is from IGDM pro

2nd is from INSTAGRAM

**Comment by freestilo** [comment]
How is it looking ?:)

**Comment by ifedapoolarewaju** [comment]
No luck so far. Specifically cos everything works as expected on my end so it's hard to fix if I can't reproduce. On my end, I get the largest image when I download. And it aligns with the way it is implemented on the app.

Do you always get low quality image for all kinds of messages you download? Or is it specifically a type of message that returns low quality image?

**Comment by freestilo** [comment]
all kinds

**Comment by freestilo** [comment]
How is it my friend ?:)

**Comment by ifedapoolarewaju** [comment]
Hi 👋🏽 

No luck with this yet.

I want to try an approach where I'll send you a version of the App that will help me investigate better.
In this version, you'll be able to download and send me a copy of the image message you receive so that I can inspect it for why we are only seeing low quality images.

I'm quite tied up today, but I'll try to share this version of the app tomorrow.

**Comment by freestilo** [comment]
Okay!:)

**Comment by freestilo** [comment]
Where i can see released updates for IGDM pro ?

**Comment by ifedapoolarewaju** [comment]
Hi, you can find the latest version on the site https://pro.igdm.me.

If you want to see all the versions released over time, you can find [them here](https://github.com/igdmapps/igdm-pro-release/releases)

**Comment by ifedapoolarewaju** [comment]
Hi @freestilo, did you manage to update to the latest version yet?

**Comment by freestilo** [comment]
![image](https://github.com/igdmapps/igdm-pro-release/assets/72163473/580dc32a-b157-4d0f-8d43-63d6670d57fb)
it shows only 3.0.0

**Comment by ifedapoolarewaju** [comment]
@freestilo when you click on the *Windows* option, it will download the latest version 3.0.18.

**Comment by freestilo** [comment]
![image](https://github.com/igdmapps/igdm-pro-release/assets/72163473/ec24393d-6ed2-40cf-b70c-400c2f0c0575)
it wont let me load up app, this is like for 10 minutes

**Comment by ifedapoolarewaju** [comment]
Hmm ... has this been what you experienced before you updated as well?

**Comment by freestilo** [comment]
Nope

**Comment by ifedapoolarewaju** [comment]
So it was working fine before you installed this update?

**Comment by freestilo** [comment]
Yes

**Comment by ifedapoolarewaju** [comment]
I have released a new version [v3.0.19](https://github.com/igdmapps/igdm-pro-release/releases/download/v3.0.19/IGdm-Pro-Setup-3.0.19.exe) here. This should fix the issue. I have also updated the version number that appears on the [pro.igdm.me](https://pro.igdm.me) website so it's less confusing

**Comment by freestilo** [comment]
It loaded up, but pictures are same in low quality still when i downloaded them - 
![image](https://github.com/igdmapps/igdm-pro-release/assets/72163473/ef25a60b-71fd-4e22-8276-11b0c7dbc42f)

**Comment by freestilo** [comment]
Whenever i open up reels from someone, its in high quality even when i download it

**Comment by ifedapoolarewaju** [comment]
> It loaded up, but pictures are same in low quality still when i downloaded them -

Yeah I didn't release a fix for it yet.

So I have created a special version that can help me investigate this issue better.
But I need to send you the download link of this version directly, since I'm not releasing it to the public.
Could you please send a "Hi" message to my email address (i****@***.com) so I can then reply you with the download link?

Let me know once you've sent it, just in case it ends up in my spam or something.

**Comment by Martin7Varga** [comment]
hello, just want to let you know that that issue with image quality still exists. I have the same issue
